# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/update-lgtm-formula.sh from a kunkka19xx/lgtm release's
# SHA256SUMS. Edit the script, not this file - a hand-edited checksum is a
# checksum nothing verified.
class Lgtm < Formula
  desc "Read what your coding agent just wrote, and point at the lines when you reply"
  homepage "https://github.com/kunkka19xx/lgtm"
  version "0.1.0"
  license "Apache-2.0"

  # Prebuilt, one binary per target. lgtm has no C dependencies and cross
  # compiles from one runner, so the release carries all four rather than
  # asking a user for a Zig toolchain.
  on_macos do
    on_arm do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.0/lgtm-aarch64-macos.tar.gz"
      sha256 "cc6dbe161c498302f5e02b3199dd9f78560bec52776ce2e54513e147d758a511"
    end
    on_intel do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.0/lgtm-x86_64-macos.tar.gz"
      sha256 "3f8b3e4735d731b353763f671bd9e22310ddacca7bd41ae870c76bacdaa535dd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.0/lgtm-aarch64-linux.tar.gz"
      sha256 "0654e6da944daf7e11545af4995651acfa2511bcee51450c1cc11254d3a8018d"
    end
    on_intel do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.0/lgtm-x86_64-linux.tar.gz"
      sha256 "eb79d2c8e20650cc04ea05749250c160eb409c78643dad391f2f50b90a3f77f7"
    end
  end

  def install
    bin.install "lgtm"
  end

  test do
    # `--version` prints the banner and exits, which is the one thing that runs
    # without a terminal, a repository or a multiplexer to talk to.
    assert_match "lgtm", shell_output("#{bin}/lgtm --version")
  end
end
