# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/update-lgtm-formula.sh from a kunkka19xx/lgtm release's
# SHA256SUMS. Edit the script, not this file - a hand-edited checksum is a
# checksum nothing verified.
class Lgtm < Formula
  desc "Read what your coding agent just wrote, and point at the lines when you reply"
  homepage "https://github.com/kunkka19xx/lgtm"
  license "Apache-2.0"

  # Prebuilt, one binary per target. lgtm has no C dependencies and cross
  # compiles from one runner, so the release carries all four rather than
  # asking a user for a Zig toolchain.
  on_macos do
    on_arm do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.1/lgtm-aarch64-macos.tar.gz"
      sha256 "1ec1839900b12b347f38f883ab01a77e6d1ee30c2a61e27a3ca7346949045b5e"
    end
    on_intel do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.1/lgtm-x86_64-macos.tar.gz"
      sha256 "1ddd9ade9d2812e92bd1e765796f71f454dfa601e1099246f5dd83649d3e74e4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.1/lgtm-aarch64-linux.tar.gz"
      sha256 "47e2f6938ed889365b15516ea03e5c192a01bb6078ada77489e432dd8ec608a6"
    end
    on_intel do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.1/lgtm-x86_64-linux.tar.gz"
      sha256 "d3671f1a4722e3789f04c92a7410a338cca4720848841c36bedfed0c3edbb6ff"
    end
  end

  def install
    bin.install "lgtm"
  end

  test do
    # `--version` prints the banner and exits, which is the one thing that runs
    # without a terminal, a repository or a multiplexer to talk to.
    assert_match "lgtm", shell_output("#{bin}/lgtm --version")
  end
end
