# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/update-lgtm-formula.sh from a kunkka19xx/lgtm release's
# SHA256SUMS. Edit the script, not this file - a hand-edited checksum is a
# checksum nothing verified.
class Lgtm < Formula
  desc "Read what your coding agent just wrote, and point at the lines when you reply"
  homepage "https://github.com/kunkka19xx/lgtm"
  license "Apache-2.0"

  # Prebuilt, one binary per target. lgtm has no C dependencies and cross
  # compiles from one runner, so the release carries all four rather than
  # asking a user for a Zig toolchain.
  on_macos do
    on_arm do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.4/lgtm-aarch64-macos.tar.gz"
      sha256 "f54cc8bd17618adb107861a0b8b1a43e5bab72ae6d7ef262de3504352fdd485b"
    end
    on_intel do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.4/lgtm-x86_64-macos.tar.gz"
      sha256 "8fa1dd3d9cae6c01a964195cb85d4f5472c218997eeb2ec3339c048ae42f8efe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.4/lgtm-aarch64-linux.tar.gz"
      sha256 "2ec30e22b496fb7232ccdee546ee026c44402b2d28f29615b926753f7c0c1ef4"
    end
    on_intel do
      url "https://github.com/kunkka19xx/lgtm/releases/download/v0.1.4/lgtm-x86_64-linux.tar.gz"
      sha256 "999b7d1ddac09d9d72e62e8460681527476b1ebfe9ef684b0b7e0f802adf66c1"
    end
  end

  def install
    bin.install "lgtm"
  end

  test do
    # `--version` prints the banner and exits, which is the one thing that runs
    # without a terminal, a repository or a multiplexer to talk to.
    assert_match "lgtm", shell_output("#{bin}/lgtm --version")
  end
end
